# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mail_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
